#para correrlo me pongo en la carpeta del dockercomposeconfig y ejecuto:
#  docker compose up -d
version: '3.1'

services:
  db:
    container_name: BaseDatosBackEndDesarrolloWeb
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: proyecto