#para correrlo me pongo en la carpeta del dockercomposeconfig y ejecuto:
#  docker compose up -d

version: '3.1'

services:
  mongodb:
    image: mongo
    container_name: my-mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: backendproyect
      MONGO_INITDB_ROOT_PASSWORD: dwym2023
    networks:
      - my-network

networks:
  my-network: