version: '3.8'
services:
  db:
    container_name: "BasedeDatosMySQL"
    image: mysql:latest
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: proyecto
      MYSQL_DATABASE: proyectoback    

